export const heroContent = {
  id: 'hero',
  title: 'TENGU',
  headingLine1: 'We don\'t sell hours.',
  headingWord: 'systems',
  headingLine2: 'that work for you.',
  headingMiddle: 'We build',
  description: 'We build systems that work for you.',
  kicker: 'Development · AI · Automation · Cloud · Consulting',
  cta: { label: 'View services', href: '#servicios' },
  ctaSecundario: { label: 'Free consultation', href: 'https://wa.me/5491151383860' },
}

export const navigationLinks = [
  { href: '/#servicios', label: 'Services' },
  { href: '/#proyectos', label: 'Projects' },
  { href: '/academia', label: 'Academy' },
  { href: '/blog', label: 'Blog' },
  { href: '/marketplace', label: 'Marketplace' },
  { href: '/#sobre', label: 'About' },
]

export const services = [
  {
    numero: '01',
    titulo: 'Web & mobile development',
    descripcion: 'Modern, scalable applications. Full-stack without technical debt from the very first sprint.',
    tags: ['Next.js', 'React', 'FastAPI', 'Django'],
    url: '#',
  },
  {
    numero: '02',
    titulo: 'AI & intelligent agents',
    descripcion: 'Chatbots, agents and generative workflows integrated into the business. Claude, Groq, local Ollama.',
    tags: ['LangChain', 'Claude', 'Groq', 'Ollama'],
    url: '#',
  },
  {
    numero: '03',
    titulo: 'Process automation',
    descripcion: 'RPA, pipelines and integrations that precisely eliminate repetitive manual work.',
    tags: ['RPA', 'n8n', 'Workflows', 'Webhooks'],
    url: '#',
  },
  {
    numero: '04',
    titulo: 'Custom ERP & CRM',
    descripcion: 'Proprietary systems with no third-party licenses. True multitenancy for corporate groups.',
    tags: ['Prisma', 'PostgreSQL', 'Supabase'],
    url: '#',
  },
  {
    numero: '05',
    titulo: 'Cloud infrastructure',
    descripcion: 'Architecture that scales with your business. AWS, GCP, Azure, Docker, Kubernetes.',
    tags: ['AWS', 'GCP', 'Docker', 'K8s'],
    url: '#',
  },
  {
    numero: '06',
    titulo: 'Data & strategic consulting',
    descripcion: 'Dashboards, analytics and technology roadmap aligned with your business objectives.',
    tags: ['Spark', 'BI', 'Analytics', 'Strategy'],
    url: '#',
  },
]

export const projects = [
  {
    nombre: 'AVATAR',
    categoria: 'Generative AI · Own hardware',
    descripcion: 'Photorealistic digital influencer generation platform. Custom pipeline on ComfyUI with Flux.1 and RealVisXL, LoRA for consistent facial identity, face swap via ReActor and video generation.',
    stack: ['ComfyUI', 'Flux.1', 'RealVisXL', 'LoRA', 'ReActor', 'FastAPI', 'Redis'],
    badge: 'Generative AI',
    badgeColor: 'red',
    url: '#',
  },
  {
    nombre: 'Triskellium',
    categoria: 'Multitenancy SaaS · Corporate groups',
    descripcion: 'Multitenancy SaaS ecosystem for corporate groups. Unifies ERP, AgentFlow, BuscarEmpleo and Parliamo with centralized authentication and PostgreSQL schema-based multitenancy.',
    stack: ['FastAPI', 'React', 'PostgreSQL', 'Redis', 'Docker'],
    badge: 'Ecosystem',
    badgeColor: 'blue',
    url: '#',
  },
  {
    nombre: 'ERP Multiempresa',
    categoria: 'Full management · Gastronomy · Retail',
    descripcion: 'Management system for groups with multiple locations. Consolidated vision, unit-level operational management, company and role-based access control, approval flows and performance comparison.',
    stack: ['FastAPI', 'PostgreSQL', 'React', 'Docker', 'Multitenancy'],
    badge: 'Ecosystem',
    badgeColor: 'blue',
    url: '#',
  },
  {
    nombre: 'AgentFlow',
    categoria: 'Automation · AI Agents · Workflows',
    descripcion: 'AI agent-driven automation platform. Build autonomous workflows with specialized agents on the Triskellium ecosystem. Hybrid Claude API + local Ollama integration.',
    stack: ['Claude API', 'Ollama', 'FastAPI', 'React', 'LangChain'],
    badge: 'Ecosystem',
    badgeColor: 'blue',
    url: '#',
  },
  {
    nombre: 'BuscarEmpleo',
    categoria: 'B2B2C Job portal · AI matching',
    descripcion: 'AI-powered job matching portal for operational roles in Argentina. Free for candidates, companies pay monthly subscription. 40+ active users, 2 subscribed companies with active MRR.',
    stack: ['Next.js', 'Supabase', 'FastAPI', 'AI Matching'],
    badge: 'Platform',
    badgeColor: 'green',
    url: '#',
  },
  {
    nombre: 'Parliamo',
    categoria: 'Real-time translation · Multilingual',
    descripcion: 'Real-time translation for multilingual environments. Gastronomy, tourism, job interviews and languages. Push-to-talk with Whisper and Claude/Google TTS for voice synthesis.',
    stack: ['FastAPI', 'React PWA', 'Whisper', 'Claude', 'Google TTS'],
    badge: 'Ecosystem',
    badgeColor: 'blue',
    url: '#',
  },
  {
    nombre: 'ANIMA',
    categoria: 'Autonomous multi-agent · R&D',
    descripcion: 'Autonomous multi-agent research architecture. Hierarchy: The Queen (master agent) + Specialized Council + Directors + Operational Teams. Episodic memory, fitness ranking and autoDream system.',
    stack: ['Claude API', 'Ollama', 'Qwen2.5', 'Phi-3 Mini', 'FastAPI'],
    badge: 'R&D',
    badgeColor: 'red',
    url: '#',
  },
  {
    nombre: 'Prospector',
    categoria: 'Automated prospecting · Outreach',
    descripcion: 'Automated prospecting and outreach tool. Lead scraping, data enrichment and contact sequences to feed the ecosystem commercial pipeline.',
    stack: ['FastAPI', 'Next.js 14', 'Tailwind', 'Scraping'],
    badge: null,
    badgeColor: null,
    url: '#',
  },
  {
    nombre: 'Affiliate Radar',
    categoria: 'Affiliate intelligence · Opportunity score',
    descripcion: 'Intelligence platform for affiliate marketing. Integrates MercadoLibre, Google Trends, Amazon BSR and Hotmart/ClickBank in a unified pipeline with a 0–100 opportunity score.',
    stack: ['FastAPI', 'Next.js 14', 'Docker', 'Cloudflare', 'pytrends'],
    badge: null,
    badgeColor: null,
    url: '#',
  },
  {
    nombre: 'Okuri Okami',
    categoria: 'Agency · Digital marketing · Design',
    descripcion: 'Digital marketing and graphic design agency. Content strategy, brand design, social media management and Meta campaigns for brands with a strong identity.',
    stack: ['Meta Ads', 'Brand design', 'Content', 'Social Media'],
    badge: null,
    badgeColor: null,
    url: '#',
  },
]

export const aboutContent = {
  heading: 'Who is behind Tengu?',
  paragraphs: [
    'Walter Matías Amengual — founder and technical lead of Tengu. Solutions engineer focused on software development, artificial intelligence and process automation. Based in Buenos Aires.',
    'Tengu is not an agency. It is a proprietary ecosystem of technology products and a team that supports companies that need to scale without adding complexity. Every project we take on has the same standard: flawless execution, long-term vision.',
    'We develop custom cross-platform software, integrate generative AI into existing workflows, automate operational processes and build management tools with full control.',
  ],
  highlight: 'We don\'t sell hours. We build systems and support decisions. Robust technology, strategic thinking and measurable results.',
  supportNote: 'Backed by a team of specialists in marketing, sales and graphic design.',
  contacto: {
    whatsapp: '+54 9 11 5138 3860',
    email: 'ventas@tengu.com.ar',
    instagram: '@tengu.com.ar',
    linkedin: 'Walter Matías Amengual',
    ubicacion: 'Buenos Aires · Argentina',
  },
}

export const metricas = [
  { valor: '100', sufijo: '+', label: 'Own projects' },
  { valor: '6', sufijo: '', label: 'Disciplines' },
  { valor: 'MRR', sufijo: '+', label: 'Active revenue' },
  { valor: '24', sufijo: 'h', label: 'Response time' },
  { valor: 'USA', sufijo: '+', label: 'Regional reach' },
]
