export const heroContent = {
  id: 'hero',
  title: 'TENGU',
  headingLine1: 'No vendemos horas.',
  headingWord: 'sistemas',
  headingLine2: 'que trabajan por vos.',
  headingMiddle: 'Construimos',
  description: 'Construimos sistemas que trabajan por vos.',
  kicker: 'Desarrollo · IA · Automatización · Cloud · Consultoría',
  cta: { label: 'Ver servicios', href: '#servicios' },
  ctaSecundario: { label: 'Consulta gratuita', href: 'https://wa.me/5491151383860' },
}

export const navigationLinks = [
  { href: '/#servicios', label: 'Servicios' },
  { href: '/#proyectos', label: 'Proyectos' },
  { href: '/academia', label: 'Academia' },
  { href: '/blog', label: 'Blog' },
  { href: '/marketplace', label: 'Marketplace' },
  { href: '/#sobre', label: 'Nosotros' },
]

export const services = [
  {
    numero: '01',
    titulo: 'Desarrollo web y mobile',
    descripcion: 'Aplicaciones modernas y escalables. Full-stack sin deuda técnica desde el primer sprint.',
    tags: ['Next.js', 'React', 'FastAPI', 'Django'],
    url: '#',
  },
  {
    numero: '02',
    titulo: 'IA y agentes inteligentes',
    descripcion: 'Chatbots, agentes y flujos generativos integrados al negocio. Claude, Groq, Ollama local.',
    tags: ['LangChain', 'Claude', 'Groq', 'Ollama'],
    url: '#',
  },
  {
    numero: '03',
    titulo: 'Automatización de procesos',
    descripcion: 'RPA, pipelines e integraciones que eliminan trabajo manual repetitivo con precisión.',
    tags: ['RPA', 'n8n', 'Workflows', 'Webhooks'],
    url: '#',
  },
  {
    numero: '04',
    titulo: 'ERP y CRM a medida',
    descripcion: 'Sistemas propios sin licencias de terceros. Multitenancy real para grupos empresariales.',
    tags: ['Prisma', 'PostgreSQL', 'Supabase'],
    url: '#',
  },
  {
    numero: '05',
    titulo: 'Infraestructura cloud',
    descripcion: 'Arquitectura que crece con tu negocio. AWS, GCP, Azure, Docker, Kubernetes.',
    tags: ['AWS', 'GCP', 'Docker', 'K8s'],
    url: '#',
  },
  {
    numero: '06',
    titulo: 'Data & consultoría estratégica',
    descripcion: 'Dashboards, analytics y roadmap tecnológico alineado a los objetivos del negocio.',
    tags: ['Spark', 'BI', 'Analytics', 'Strategy'],
    url: '#',
  },
]

export const projects = [
  {
    nombre: 'AVATAR',
    categoria: 'IA generativa · Hardware propio',
    descripcion: 'Plataforma de generación de influencers digitales fotorrealistas. Pipeline propio sobre ComfyUI con Flux.1 y RealVisXL, LoRA para identidad facial consistente, face swap via ReActor y generación de video.',
    stack: ['ComfyUI', 'Flux.1', 'RealVisXL', 'LoRA', 'ReActor', 'FastAPI', 'Redis'],
    badge: 'IA generativa',
    badgeColor: 'red',
    url: '#',
  },
  {
    nombre: 'Triskellium',
    categoria: 'SaaS multitenancy · Grupos empresariales',
    descripcion: 'Ecosistema SaaS multitenancy para grupos empresariales. Unifica ERP, AgentFlow, BuscarEmpleo y Parliamo con autenticación centralizada y multitenancy por schema PostgreSQL.',
    stack: ['FastAPI', 'React', 'PostgreSQL', 'Redis', 'Docker'],
    badge: 'Ecosistema',
    badgeColor: 'blue',
    url: '#',
  },
  {
    nombre: 'ERP Multiempresa',
    categoria: 'Gestión integral · Gastronómico · Retail',
    descripcion: 'Sistema de gestión para grupos con múltiples locales. Visión consolidada, gestión operativa por unidad, control de accesos por empresa y rol, flujos de aprobación y comparativa de performance.',
    stack: ['FastAPI', 'PostgreSQL', 'React', 'Docker', 'Multitenancy'],
    badge: 'Ecosistema',
    badgeColor: 'blue',
    url: '#',
  },
  {
    nombre: 'AgentFlow',
    categoria: 'Automatización · Agentes IA · Workflows',
    descripcion: 'Plataforma de automatización mediante agentes IA. Construye flujos de trabajo autónomos con agentes especializados sobre el ecosistema Triskellium. Integración híbrida Claude API + Ollama local.',
    stack: ['Claude API', 'Ollama', 'FastAPI', 'React', 'LangChain'],
    badge: 'Ecosistema',
    badgeColor: 'blue',
    url: '#',
  },
  {
    nombre: 'BuscarEmpleo',
    categoria: 'Portal laboral B2B2C · Matching con IA',
    descripcion: 'Portal de matching laboral con IA para roles operativos en Argentina. Candidatos gratis, empresas pagan suscripción mensual. 40+ usuarios activos, 2 empresas suscriptas con MRR activo.',
    stack: ['Next.js', 'Supabase', 'FastAPI', 'IA Matching'],
    badge: 'Plataforma',
    badgeColor: 'green',
    url: '#',
  },
  {
    nombre: 'Parliamo',
    categoria: 'Traducción en tiempo real · Multilingüe',
    descripcion: 'Traducción en tiempo real para entornos multilingüe. Gastronomía, turismo, entrevistas laborales e idiomas. Push-to-talk con Whisper y Claude/Google TTS para síntesis de voz.',
    stack: ['FastAPI', 'React PWA', 'Whisper', 'Claude', 'Google TTS'],
    badge: 'Ecosistema',
    badgeColor: 'blue',
    url: '#',
  },
  {
    nombre: 'ANIMA',
    categoria: 'Multi-agente autónomo · I+D',
    descripcion: 'Arquitectura multi-agente autónoma de investigación. Jerarquía: La Reina (agente maestro) + Consejo especializado + Directores + Equipos operacionales. Memoria episódica, ranking por fitness y sistema autoDream.',
    stack: ['Claude API', 'Ollama', 'Qwen2.5', 'Phi-3 Mini', 'FastAPI'],
    badge: 'I+D',
    badgeColor: 'red',
    url: '#',
  },
  {
    nombre: 'Prospector',
    categoria: 'Prospección automatizada · Outreach',
    descripcion: 'Herramienta de prospección y outreach automatizado. Scraping de leads, enriquecimiento de datos y secuencias de contacto para alimentar el pipeline comercial del ecosistema.',
    stack: ['FastAPI', 'Next.js 14', 'Tailwind', 'Scraping'],
    badge: null,
    badgeColor: null,
    url: '#',
  },
  {
    nombre: 'Affiliate Radar',
    categoria: 'Inteligencia de afiliados · Score de oportunidad',
    descripcion: 'Plataforma de inteligencia para marketing de afiliados. Integra MercadoLibre, Google Trends, Amazon BSR y Hotmart/ClickBank en un pipeline unificado con score de oportunidad 0–100.',
    stack: ['FastAPI', 'Next.js 14', 'Docker', 'Cloudflare', 'pytrends'],
    badge: null,
    badgeColor: null,
    url: '#',
  },
  {
    nombre: 'Okuri Okami',
    categoria: 'Agencia · Marketing digital · Diseño',
    descripcion: 'Agencia de marketing digital y diseño gráfico. Estrategia de contenidos, diseño de marca, gestión de redes sociales y campañas Meta para marcas con identidad fuerte.',
    stack: ['Meta Ads', 'Diseño de marca', 'Contenidos', 'Social Media'],
    badge: null,
    badgeColor: null,
    url: '#',
  },
]

export const aboutContent = {
  heading: '¿Quién está detrás de Tengu?',
  paragraphs: [
    'Walter Matías Amengual — fundador y líder técnico de Tengu. Ingeniero de soluciones con foco en desarrollo de software, inteligencia artificial y automatización de procesos. Base en Buenos Aires.',
    'Tengu no es una agencia. Es un ecosistema propio de productos tecnológicos y un equipo que acompaña a empresas que necesitan escalar sin sumar complejidad. Cada proyecto que tomamos tiene el mismo estándar: ejecución impecable, visión de largo plazo.',
    'Desarrollamos software multiplataforma a medida, integramos IA generativa en flujos de trabajo existentes, automatizamos procesos operativos y construimos herramientas de gestión con control total.',
  ],
  highlight: 'No vendemos horas. Construimos sistemas y acompañamos decisiones. Tecnología robusta, criterio estratégico y resultados medibles.',
  supportNote: 'Respaldado por un equipo de especialistas en marketing, ventas y diseño gráfico.',
  contacto: {
    whatsapp: '+54 9 11 5138 3860',
    email: 'ventas@tengu.com.ar',
    instagram: '@tengu.com.ar',
    linkedin: 'Walter Matías Amengual',
    ubicacion: 'Buenos Aires · Argentina',
  },
}

export const metricas = [
  { valor: '100', sufijo: '+', label: 'Proyectos propios' },
  { valor: '6', sufijo: '', label: 'Disciplinas' },
  { valor: 'MRR', sufijo: '+', label: 'Revenue activo' },
  { valor: '24', sufijo: 'h', label: 'Respuesta' },
  { valor: 'ARG', sufijo: '+', label: 'Alcance regional' },
]
