export const heroContent = {
  id: 'hero',
  title: 'TENGU',
  headingLine1: 'Non vendiamo ore.',
  headingWord: 'sistemi',
  headingLine2: 'che lavorano per te.',
  headingMiddle: 'Costruiamo',
  description: 'Costruiamo sistemi che lavorano per te.',
  kicker: 'Sviluppo · IA · Automazione · Cloud · Consulenza',
  cta: { label: 'Vedi servizi', href: '#servicios' },
  ctaSecundario: { label: 'Consulenza gratuita', href: 'https://wa.me/5491151383860' },
}

export const navigationLinks = [
  { href: '/#servicios', label: 'Servizi' },
  { href: '/#proyectos', label: 'Progetti' },
  { href: '/academia', label: 'Accademia' },
  { href: '/blog', label: 'Blog' },
  { href: '/marketplace', label: 'Marketplace' },
  { href: '/#sobre', label: 'Chi siamo' },
]

export const services = [
  {
    numero: '01',
    titulo: 'Sviluppo web e mobile',
    descripcion: 'Applicazioni moderne e scalabili. Full-stack senza debito tecnico fin dal primo sprint.',
    tags: ['Next.js', 'React', 'FastAPI', 'Django'],
    url: '#',
  },
  {
    numero: '02',
    titulo: 'IA e agenti intelligenti',
    descripcion: 'Chatbot, agenti e flussi generativi integrati nel business. Claude, Groq, Ollama locale.',
    tags: ['LangChain', 'Claude', 'Groq', 'Ollama'],
    url: '#',
  },
  {
    numero: '03',
    titulo: 'Automazione dei processi',
    descripcion: 'RPA, pipeline e integrazioni che eliminano con precisione il lavoro manuale ripetitivo.',
    tags: ['RPA', 'n8n', 'Workflows', 'Webhooks'],
    url: '#',
  },
  {
    numero: '04',
    titulo: 'ERP e CRM su misura',
    descripcion: 'Sistemi proprietari senza licenze di terze parti. Multitenancy reale per gruppi aziendali.',
    tags: ['Prisma', 'PostgreSQL', 'Supabase'],
    url: '#',
  },
  {
    numero: '05',
    titulo: 'Infrastruttura cloud',
    descripcion: 'Architettura che cresce con il tuo business. AWS, GCP, Azure, Docker, Kubernetes.',
    tags: ['AWS', 'GCP', 'Docker', 'K8s'],
    url: '#',
  },
  {
    numero: '06',
    titulo: 'Data & consulenza strategica',
    descripcion: 'Dashboard, analytics e roadmap tecnologica allineata agli obiettivi del business.',
    tags: ['Spark', 'BI', 'Analytics', 'Strategy'],
    url: '#',
  },
]

export const projects = [
  {
    nombre: 'AVATAR',
    categoria: 'IA generativa · Hardware proprietario',
    descripcion: 'Piattaforma di generazione di influencer digitali fotorealistici. Pipeline proprietaria su ComfyUI con Flux.1 e RealVisXL, LoRA per identità facciale coerente, face swap via ReActor e generazione video.',
    stack: ['ComfyUI', 'Flux.1', 'RealVisXL', 'LoRA', 'ReActor', 'FastAPI', 'Redis'],
    badge: 'IA generativa',
    badgeColor: 'red',
    url: '#',
  },
  {
    nombre: 'Triskellium',
    categoria: 'SaaS multitenancy · Gruppi aziendali',
    descripcion: 'Ecosistema SaaS multitenancy per gruppi aziendali. Unifica ERP, AgentFlow, BuscarEmpleo e Parliamo con autenticazione centralizzata e multitenancy per schema PostgreSQL.',
    stack: ['FastAPI', 'React', 'PostgreSQL', 'Redis', 'Docker'],
    badge: 'Ecosistema',
    badgeColor: 'blue',
    url: '#',
  },
  {
    nombre: 'ERP Multiempresa',
    categoria: 'Gestione integrale · Ristorazione · Retail',
    descripcion: 'Sistema di gestione per gruppi con più sedi. Visione consolidata, gestione operativa per unità, controllo accessi per azienda e ruolo, flussi di approvazione e confronto performance.',
    stack: ['FastAPI', 'PostgreSQL', 'React', 'Docker', 'Multitenancy'],
    badge: 'Ecosistema',
    badgeColor: 'blue',
    url: '#',
  },
  {
    nombre: 'AgentFlow',
    categoria: 'Automazione · Agenti IA · Workflows',
    descripcion: 'Piattaforma di automazione tramite agenti IA. Costruisce flussi di lavoro autonomi con agenti specializzati sull\'ecosistema Triskellium. Integrazione ibrida Claude API + Ollama locale.',
    stack: ['Claude API', 'Ollama', 'FastAPI', 'React', 'LangChain'],
    badge: 'Ecosistema',
    badgeColor: 'blue',
    url: '#',
  },
  {
    nombre: 'BuscarEmpleo',
    categoria: 'Portale lavoro B2B2C · Matching con IA',
    descripcion: 'Portale di matching lavorativo con IA per ruoli operativi in Argentina. Candidati gratis, le aziende pagano un abbonamento mensile. 40+ utenti attivi, 2 aziende abbonate con MRR attivo.',
    stack: ['Next.js', 'Supabase', 'FastAPI', 'IA Matching'],
    badge: 'Piattaforma',
    badgeColor: 'green',
    url: '#',
  },
  {
    nombre: 'Parliamo',
    categoria: 'Traduzione in tempo reale · Multilingue',
    descripcion: 'Traduzione in tempo reale per ambienti multilingue. Ristorazione, turismo, colloqui di lavoro e lingue. Push-to-talk con Whisper e Claude/Google TTS per la sintesi vocale.',
    stack: ['FastAPI', 'React PWA', 'Whisper', 'Claude', 'Google TTS'],
    badge: 'Ecosistema',
    badgeColor: 'blue',
    url: '#',
  },
  {
    nombre: 'ANIMA',
    categoria: 'Multi-agente autonomo · R&S',
    descripcion: 'Architettura multi-agente autonoma di ricerca. Gerarchia: La Regina (agente maestro) + Consiglio specializzato + Direttori + Team operativi. Memoria episodica, ranking per fitness e sistema autoDream.',
    stack: ['Claude API', 'Ollama', 'Qwen2.5', 'Phi-3 Mini', 'FastAPI'],
    badge: 'R&S',
    badgeColor: 'red',
    url: '#',
  },
  {
    nombre: 'Prospector',
    categoria: 'Prospezione automatizzata · Outreach',
    descripcion: 'Strumento di prospezione e outreach automatizzato. Scraping di lead, arricchimento dati e sequenze di contatto per alimentare la pipeline commerciale dell\'ecosistema.',
    stack: ['FastAPI', 'Next.js 14', 'Tailwind', 'Scraping'],
    badge: null,
    badgeColor: null,
    url: '#',
  },
  {
    nombre: 'Affiliate Radar',
    categoria: 'Intelligence affiliati · Punteggio opportunità',
    descripcion: 'Piattaforma di intelligence per l\'affiliate marketing. Integra MercadoLibre, Google Trends, Amazon BSR e Hotmart/ClickBank in una pipeline unificata con punteggio opportunità 0–100.',
    stack: ['FastAPI', 'Next.js 14', 'Docker', 'Cloudflare', 'pytrends'],
    badge: null,
    badgeColor: null,
    url: '#',
  },
  {
    nombre: 'Okuri Okami',
    categoria: 'Agenzia · Marketing digitale · Design',
    descripcion: 'Agenzia di marketing digitale e design grafico. Strategia dei contenuti, design del brand, gestione dei social media e campagne Meta per brand con un\'identità forte.',
    stack: ['Meta Ads', 'Brand design', 'Contenuti', 'Social Media'],
    badge: null,
    badgeColor: null,
    url: '#',
  },
]

export const aboutContent = {
  heading: 'Chi c\'è dietro Tengu?',
  paragraphs: [
    'Walter Matías Amengual — fondatore e responsabile tecnico di Tengu. Ingegnere di soluzioni con focus sullo sviluppo software, l\'intelligenza artificiale e l\'automazione dei processi. Con base a Buenos Aires.',
    'Tengu non è un\'agenzia. È un ecosistema proprietario di prodotti tecnologici e un team che accompagna le aziende che hanno bisogno di crescere senza aggiungere complessità. Ogni progetto che prendiamo ha lo stesso standard: esecuzione impeccabile, visione a lungo termine.',
    'Sviluppiamo software multipiattaforma su misura, integriamo l\'IA generativa nei flussi di lavoro esistenti, automatizziamo i processi operativi e costruiamo strumenti di gestione con pieno controllo.',
  ],
  highlight: 'Non vendiamo ore. Costruiamo sistemi e accompagniamo le decisioni. Tecnologia robusta, criterio strategico e risultati misurabili.',
  supportNote: 'Supportato da un team di specialisti in marketing, vendite e design grafico.',
  contacto: {
    whatsapp: '+54 9 11 5138 3860',
    email: 'ventas@tengu.com.ar',
    instagram: '@tengu.com.ar',
    linkedin: 'Walter Matías Amengual',
    ubicacion: 'Buenos Aires · Argentina',
  },
}

export const metricas = [
  { valor: '100', sufijo: '+', label: 'Progetti propri' },
  { valor: '6', sufijo: '', label: 'Discipline' },
  { valor: 'MRR', sufijo: '+', label: 'Ricavi attivi' },
  { valor: '24', sufijo: 'h', label: 'Risposta' },
  { valor: 'ITA', sufijo: '+', label: 'Copertura regionale' },
]
